---
- name: Deploy Slab.AI Application Stack
  hosts: jigar-G4-slab-ai-server
  become: yes

  tasks:
    - name: Ensure Docker network exists
      command: docker network create slabai-net
      ignore_errors: yes

    - name: Login to AWS ECR
      shell: |
        aws ecr get-login-password --region us-west-2 \
          | docker login --username AWS --password-stdin 975050024946.dkr.ecr.us-west-2.amazonaws.com
      register: ecr_login

    - debug:
        var: ecr_login.stdout

    # ----------------------
    # Infrastructure services
    # ----------------------

    - name: Start MongoDB container
      docker_container:
        name: mongo
        image: mongo:6
        state: started
        restart_policy: always
        networks:
          - name: slabai-net
        published_ports:
          - "27017:27017"

    - name: Start Redis container
      docker_container:
        name: redis-server
        image: redis:6
        state: started
        restart_policy: always
        networks:
          - name: slabai-net
        published_ports:
          - "6379:6379"

    # ----------------------
    # Application services
    # ----------------------

    - name: Deploy Project Service
      docker_container:
        name: project-service
        image: 975050024946.dkr.ecr.us-west-2.amazonaws.com/jigar-slab-ai/project-service:latest
        state: started
        restart_policy: always
        networks:
          - name: slabai-net
        published_ports:
          - "7005:7005"
        env:
          PORT: "7005"
          MONGO_URI: "mongodb://mongo:27017/slabai"
          REDIS_URI: "redis://redis-server:6379"
          AWS_BUCKET_NAME: "slab-ai-demo-bucket"
          AWS_REGION: "us-west-2"

    - name: Deploy User Service
      docker_container:
        name: user-service
        image: 975050024946.dkr.ecr.us-west-2.amazonaws.com/jigar-slab-ai/user-service:latest
        state: started
        restart_policy: always
        networks:
          - name: slabai-net
        published_ports:
          - "7003:5000"
        env:
          PORT: "5000"
          MONGO_URI: "mongodb://mongo:27017/slabai"
          REDIS_URI: "redis://redis-server:6379"

    - name: Deploy Payment Service
      docker_container:
        name: payment-service
        image: 975050024946.dkr.ecr.us-west-2.amazonaws.com/jigar-slab-ai/payment-service:latest
        state: started
        restart_policy: always
        networks:
          - name: slabai-net
        published_ports:
          - "7004:5000"
        env:
          PORT: "5000"
          MONGO_URI: "mongodb://mongo:27017/slabai"
          REDIS_URI: "redis://redis-server:6379"

    - name: Deploy Frontend
      docker_container:
        name: frontend
        image: 975050024946.dkr.ecr.us-west-2.amazonaws.com/jigar-slab-ai/frontend:latest
        state: started
        restart_policy: always
        networks:
          - name: slabai-net
        published_ports:
          - "8080:80"