---
- name: Deploy Slab.AI Application Stack
  hosts: app_servers
  become: yes

  vars:
    aws_region: "us-west-2"
    aws_account_id: "975050024946"
    ecr_prefix: "{{ aws_account_id }}.dkr.ecr.{{ aws_region }}.amazonaws.com/jigar-slab-ai"

  tasks:
    - name: Ensure old containers are removed
      shell: |
        docker rm -f frontend payment-service project-service user-service mongo redis-server || true

    - name: Run MongoDB
      shell: |
        docker run -d --name mongo -p 27017:27017 \
          -v mongo_data:/data/db \
          mongo:6

    - name: Run Redis
      shell: |
        docker run -d --name redis-server -p 6379:6379 redis:6

    - name: Deploy Payment Service
      shell: |
        docker run -d --name payment-service -p 7001:5000 \
          --env-file /home/ubuntu/payment.env \
          --env MONGO_URI=mongodb://mongo:27017/slabai \
          --env REDIS_HOST=redis-server \
          --env REDIS_PORT=6379 \
          --link mongo:mongo --link redis-server:redis \
          {{ ecr_prefix }}/payment-service:latest

    - name: Deploy Project Service
      shell: |
        docker run -d --name project-service -p 7002:7005 \
          --env-file /home/ubuntu/project.env \
          --env MONGO_URI=mongodb://mongo:27017/slabai \
          --env REDIS_HOST=redis-server \
          --env REDIS_PORT=6379 \
          --link mongo:mongo --link redis-server:redis \
          {{ ecr_prefix }}/project-service:latest

    - name: Deploy User Service
      shell: |
        docker run -d --name user-service -p 7003:5000 \
          --env-file /home/ubuntu/user.env \
          --env MONGO_URI=mongodb://mongo:27017/slabai \
          --env REDIS_HOST=redis-server \
          --env REDIS_PORT=6379 \
          --link mongo:mongo --link redis-server:redis \
          {{ ecr_prefix }}/user-service:latest

    - name: Deploy Frontend
      shell: |
        docker run -d --name frontend -p 8080:80 \
          --link project-service:project-service \
          --link user-service:user-service \
          --link payment-service:payment-service \
          {{ ecr_prefix }}/frontend:latest