---
- name: Configure Slab AI server
  hosts: app_servers
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Enable & start Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Download latest stable kubectl binary
      get_url:
        url: "https://dl.k8s.io/release/{{ lookup('url', 'https://dl.k8s.io/release/stable.txt') }}/bin/linux/amd64/kubectl"
        dest: /tmp/kubectl
        mode: '0755'

    - name: Install kubectl
      command: install -o root -g root -m 0755 /tmp/kubectl /usr/local/bin/kubectl

    - name: Verify kubectl installation
      command: kubectl version --client
      register: kubectl_version
      changed_when: false

    - debug:
        msg: "Kubectl installed successfully: {{ kubectl_version.stdout }}"

