---
- name: Configure Slab AI server
  hosts: app_servers
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Enable & start Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Install kubectl
      apt:
        name: kubectl
        state: present
